### ISSUE TITLE
Milestone v2

### ISSUE THREAD

**Issue by pixelastic** [algolia/docsearch-scraper#33]
Here is the checklist to things to be done before releasing DocSearch v2. The v2 will officially be merged in the docsearch.js repo, thus making the project public. We will also update docsearch.js to v2.0 and keep the two projects in sync.
## Improvements to the scraper
- [x] Allowing global selectors #32
- [x] Allowing XPath for global selectors #31
- [x] Allow the removing of some unwanted characters in selector results #34
- [x] Allowing defaut_value for selectors #12 
- [x] Allow bypassing the lvl0 #38
- [ ] Add nice test coverage badge
- [x] Update the customers waiting #35
## Improvements to the playground
- [x] Make the config editable #36
- [x] Quick switch between configs #37
## Improvements to the documentation
- [x] Update the readme with all options
- [ ] Add one or two tutorial examples for common docs (GitBook, etc)
- [ ] Generate the doc in a Jekyll website
## Final merge
- [ ] Synchronize scraper version and javascript version
- [ ] Add scraper documentation webpage to the website
- [ ] Add a `removeTitle` option on docsearch.js that automatically hide the horizontal bar (to be used with the `lvl0: None` scraper option)
